server:
  port: 9401

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ejk-form-engine?useUnicode=true&characterEncoding=utf-8&autoReconnect=true
    username: root
    password: mysql

  redis:
    host: localhost
    port: 6379

elasticsearch:
  server-url: http://localhost:9200

eureka:
  instance:
    hostname: localhost

logging:
  level:
    com:
      ns: DEBUG
