-- MySQL Script generated by MySQL Workbench
-- Tue Feb  6 15:51:57 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema form_engine
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `form_engine` ;

-- -----------------------------------------------------
-- Schema form_engine
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `form_engine` DEFAULT CHARACTER SET utf8 ;
USE `form_engine` ;

-- -----------------------------------------------------
-- Table `form_engine`.`data_item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `form_engine`.`data_item` ;

CREATE TABLE IF NOT EXISTS `form_engine`.`data_item` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `form_data_id` BIGINT(20) NOT NULL,
  `field_name` VARCHAR(128) NOT NULL COMMENT '属性名',
  `value` VARCHAR(256) NOT NULL COMMENT '属性的值',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `form_engine`.`form_data`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `form_engine`.`form_data` ;

CREATE TABLE IF NOT EXISTS `form_engine`.`form_data` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `schema_id` BIGINT(20) NOT NULL COMMENT 'form_schema表的主键',
  `value` TEXT NOT NULL COMMENT '表单对应的数据',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `form_engine`.`form_schema`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `form_engine`.`form_schema` ;

CREATE TABLE IF NOT EXISTS `form_engine`.`form_schema` (
  `id` BIGINT(20) NOT NULL,
  `designer_id` BIGINT(20) NOT NULL COMMENT '设计器id',
  `name` VARCHAR(128) NULL COMMENT '表单id',
  `value` TEXT NOT NULL COMMENT 'schema的值',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `form_engine`.`schema_item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `form_engine`.`schema_item` ;

CREATE TABLE IF NOT EXISTS `form_engine`.`schema_item` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `schema_id` BIGINT(20) NOT NULL COMMENT 'schema表的主键',
  `field_name` VARCHAR(128) NOT NULL COMMENT '属性的名字',
  `display_name` VARCHAR(128) NOT NULL COMMENT '表单属性显示的名字',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `form_engine`.`schema_item_validate`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `form_engine`.`schema_item_validate` ;

CREATE TABLE IF NOT EXISTS `form_engine`.`schema_item_validate` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `schema_item_id` BIGINT(20) NOT NULL COMMENT 'form_schema_item表的主键',
  `type` VARCHAR(64) NOT NULL COMMENT '校验类型',
  `value` VARCHAR(256) NULL COMMENT '校验模板',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
